baseurl      = "https://jansetaskin.github.io/janset_website/"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    tag      = "tags"
    series   = "series"
    category = "categories"

[languages]
  [languages.en]
    title = "Hi, it's Janset."
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "janset askin"
      logoHomeLink = "/"
      logoMark = ">"
      logoCursorColor    = "#a791b3"
      # "#959e60"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "/about"
    url        = "/about"

  [[menu.main]]
    identifier = "projects"
    name       = "/projects"
    url        = "/projects"

  # [[menu.main]]
   # identifier = "blog"
   # name       = "/blog"
   # url        = "/posts"

  [[menu.main]]
    identifier = "experience"
    name       = "/experience"
    url        = "/experience"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/janset-askin/"

  [[params.social]]
    name = "email"
    url  = "mailto:jansetaskin@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/jansetaskin"

  [[params.social]]
    name = "medium"
    url  = "https://medium.com/@jansetaskin"

  # [params.portrait]
    # path     = "static/me.png"
    # alt      = "Portrait"
    # maxWidth = "150px"

 [params.footer]
    trademark = false
    rss = false
    copyright = false
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
    ]
